apiVersion: konnect.konghq.com/v1alpha1
kind: KonnectExtension
metadata:
  name: konnect-extension
  namespace: kong
spec:
  konnect:
    controlPlane:
      ref:
        type: konnectNamespacedRef
        konnectNamespacedRef:
          # Refers to the KonnectGatewayControlPlane CR declared in
          # konnect-controlplane.yaml (same namespace). The operator
          # reconciles that CR by creating/updating the CP in Konnect.
          name: kong-cicd-demo
  clientAuth:
    certificateSecret:
      provisioning: Automatic
  konnectControlPlaneAPIAuthConfiguration:
    name: konnect-api-auth
