apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: demo-user
  namespace: httpbin
username: demo-user
spec:
  controlPlaneRef:
    type: konnectNamespacedRef
    konnectNamespacedRef:
      name: kong
      namespace: kong
